name: "TVHeadend"
guid: "3fd018e5-5e78-4e58-b280-a0c068febee0"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvheadend.png"
version: 12
targetAbi: .0
framework: "net6.0"
owner: "jellyfin"
overview: "Manage TVHeadend from Jellyfin"
description: "Manage TVHeadend from Jellyfin"
category: "LiveTV"
artifacts:
  - "TVHeadEnd.dll"
changelog: |-
  - Stop Async connection handler threads if remote host has closed the connection. (#74) @Charlese2
