name: "TVHeadend"
guid: "3fd018e5-5e78-4e58-b280-a0c068febee0"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvheadend.png"
version: 13
targetAbi: "10.9.9.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Manage TVHeadend from Jellyfin"
description: "Manage TVHeadend from Jellyfin"
category: "LiveTV"
artifacts:
  - "TVHeadEnd.dll"
changelog: |-
  - Further Release 10.9.x improvements (#92) @lomion0815
  - Readme: update build requirements (#93) @citronalco
  - Fixed link to TVHeadend image (#83) @lomion0815
  - Set correct dates for recordings (#84) @lomion0815
  - Changed HTSP field "summary" to correct name "subtitle". (#85) @lomion0815
